language: ruby
cache: bundler
rvm:
  - 2.3

sudo: false

before_install:
  - gem update --system
  - gem install bundler
  - pip3 install PyYAML
script: ./docs/generate.sh

branches:
  only:
    - better-docs

env:
  global:
    JEKYLL_ENV: production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: better-docs
  local_dir: docs/_site
  target_branch: gh-pages
