name: Build

on:
 push:
  branches:
  - 'master'
  - 'develop'
  - 'github-action'
  paths:
  - '.github/workflows/build.yml'
  - 'action.yml'
  - 'sfall/**'
 pull_request:
  branches:
  - 'master'
  - 'develop'
  paths:
  - '.github/workflows/build.yml'
  - 'action.yml'
  - 'sfall/**'

jobs:
 Build:
  name:    sfall
  runs-on: windows-2022
  steps:

  - name: Clone sfall
    uses: actions/checkout@v4

  # Action is used twice for self-testing only
  # DevXP build results are intentionally *not* included in artifact

  - name: ReleaseXP build
    id:   build
    uses: ./
    with:
     release-xp: true
     dev-xp:     false

  - name: DevXP build
    uses: ./
    with:
     release-xp: false
     dev-xp:     true

  - name:  Prepare artifacts
    run:   |
           :
           mkdir -p sfall-build

           cp artifacts/ddraw.ini sfall-build
           cp artifacts/sfall_dat/sfall.dat sfall-build
           cp "${{ steps.build.outputs.release-xp }}" sfall-build
    shell: bash

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
     name:           sfall-build
     path:           sfall-build
     retention-days: 14
