name: Sync with upstream

on:
  schedule:
    - cron: "33 7 * * *"
  workflow_dispatch: # click the button on Github repo!
  push:

jobs:
  sync_master: # master follows upstream strictly
    runs-on: ubuntu-latest
    name: Sync master with upstream/master
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull (Fast-Forward) upstream changes
        id: sync-master
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: sfall-team/sfall
          upstream_sync_branch: master
          upstream_pull_args: "--ff-only --tags"
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          shallow_since: "10 years"

  sync_better_docs:
    runs-on: ubuntu-latest
    name: Sync better-docs with upstream/master
    steps:
      - name: Checkout better-docs
        uses: actions/checkout@v3
        with:
          ref: better-docs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull (Fast-Forward) upstream changes (better-docs)
        id: sync-better-docs
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: sfall-team/sfall
          upstream_sync_branch: master
          upstream_pull_args: "--tags"
          target_sync_branch: better-docs
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          shallow_since: "10 years"
